@startuml
skinparam handwritten true
skinparam sequenceMessageAlign center
autonumber
hide footbox

actor       Developer       as user
participant    asdf    as asdf
participant    Plugin    as plugin
participant    "bin/download"    as plugin_script
entity    GitHub    as github order 100 #green

user -> asdf: asdf plugin-add go
user -> asdf: asdf install go latest
asdf -> plugin: list-latest-stable
plugin -> asdf: 1.22.4
asdf -> plugin : download 1.22.4
plugin -> plugin_script
plugin_script -> github: Download go 1.22.4
plugin_script -> plugin_script: move go to\n $ASDF_INSTALL_PATH
plugin_script -> plugin: OK
plugin -> asdf: OK

@enduml
